- hosts: webserver
  
  tasks:
    - name: Terminate ec2 instances
      ec2_instance:
        state: absent
        instance_ids: "i-08e1efcd967fa18c9"
        region: us-east-1
        wait: true
      delegate_to: localhost